language: node_js
node_js:
  - stable

install:
  - npm install
script:
  - npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: '1243087518@qq.com'
  api_key: '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'
